//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public decimal seatId { get; set; }
        public Nullable<decimal> happeningId { get; set; }
        public Nullable<bool> seatIsFree { get; set; }
        public Nullable<int> seatPrice { get; set; }
        public Nullable<int> seatRow { get; set; }
        public Nullable<int> seatColumn { get; set; }
        public Nullable<decimal> clientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Happening Happening { get; set; }
    }
}
